#!/usr/bin/env bash
# Installs UFW and blocks all incoming traffic except TCP ports 22, 443 and 80
apt-get update -y
apt-get install -y ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw --force enable
ufw status verbose
