#!/usr/bin/env bash
# Configures a brand new Ubuntu machine with Nginx and a custom X-Served-By header
apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

cat > /etc/nginx/sites-available/default << 'NGINX_CONF'
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm;

	server_name _;

	add_header X-Served-By $hostname;

	location / {
		try_files $uri $uri/ =404;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}
NGINX_CONF

service nginx restart
