#!/usr/bin/env bash
# Configures nginx to add a custom X-Served-By response header set to the server's hostname
apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/a\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

service nginx start || service nginx restart
