#!/usr/bin/env bash
# Configures nginx to add a custom X-Served-By response header set to the server's hostname
apt-get update -y
apt-get install -y nginx
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By $hostname;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx restart
