#!/usr/bin/env bash
# Installs and configures HAProxy to load balance web-01 and web-02 using roundrobin
apt-get update -y
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY_CONF'
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend web_backend

backend web_backend
	balance roundrobin
	server 7117-web-01 13.221.150.218:80 check
	server 7117-web-02 34.201.67.158:80 check
HAPROXY_CONF

echo "ENABLED=1" > /etc/default/haproxy
service haproxy restart
