#!/usr/bin/env bash
# Configures nginx with a 301 redirect from /redirect_me to another page
apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

sed -i '/server_name _;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx start || service nginx restart
